version: '3.4'

services:
  bebrand.services.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
    ports:
      - "80"
    networks:
      - webproxy
networks:
  webproxy:
    external: true